#!/usr/bin/python3
from pmapi.config import Config, get_logger
from pmapi.controllers.sync import get_sync
from pmapi.controllers.sign import post_sign
from pmapi.controllers.promote import post_promote
from pmapi.controllers.webui import post_deploy_webui
from pmapi.controllers.healthcheck import get_healthcheck
from pmapi.controllers.delete import get_completely_delete_rpm, post_delete_rpm

import os
import logging
import requests
from flask import Flask, request


logger = get_logger()


#if not Config.TOKEN:
#    data = {
#        "hostname": Config.HOSTNAME,
#        "ip": Config.IP,
#        "state": Config.STATE,
#        "url": Config.URL,
#        "service_type": Config.SERVICE_TYPE,
#        "roles": "'service', 'primemirror'",
#    }
#    logging.info("Registering Service: ".format(data))
#    r = requests.post("{}/register/service".format(Config.DEPLOYMENT_API_URI), json=data, verify=False)
#    resp = r.json()
#    if "TOKEN" in resp:
#        update_env("TOKEN", resp["TOKEN"])



